### ISSUE TITLE
receive data function errors

### ISSUE THREAD

**Issue by DavidJRichards** [deeplyembeddedWP/BeagleBone_I2C_Library#2]
The two functions used to receive i2c data, i2c_read() and i2c_read_registers() use address of read_data in call to read(), read_data is already a pointer type and does not need the & operator. These functions work for me on Beaglebone with the above edits. Thanks for a nice simple library, working well for me. David.

**Comment by vinay-divakar** [comment]
It's fixed. Thanks for pointing that out.

Cheers
Vinay
